on: [ pull_request, push ]
name: ci
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin main
    - uses: flux-framework/pr-validator@master

  ci-checks:
    runs-on: ubuntu-latest
    env:
      TAP_DRIVER_QUIET: 1
      FLUX_TEST_TIMEOUT: 300
    timeout-minutes: 20
    strategy:
      matrix:
        include:
        - name: "focal - ompi v5.0.x, chain_lint"
          image: "focal"
          ompi_branch: "v5.0.0rc12"
          openpmix_branch: "v4.2.3"
          coverage: false
          env:
            chain_lint: t
        - name: "el8 - ompi v5.0.x, distcheck"
          image: "el8"
          ompi_branch: "v5.0.0rc12"
          openpmix_branch: "v4.2.3"
          coverage: false
          create_release: true
          env:
            DISTCHECK: t
        - name: "el8 - pmix v3.2.3, ompi v4.1.4"
          image: "el8"
          ompi_branch: "v4.1.4"
          openpmix_branch: "v3.2.3"
          coverage: false
          env: {}
        - name: "coverage"
          image: "focal"
          ompi_branch: "v5.0.0rc12"
          openpmix_branch: "v4.2.3"
          coverage: true
          env:
            COVERAGE: t
        - name: "fedora34 - ompi v5.0.x"
          image: "fedora34"
          ompi_branch: "v5.0.0rc12"
          openpmix_branch: "v4.2.3"
          coverage: false
          env: {}
        - name: "focal - ompi v4.1.x"
          image: "focal"
          ompi_branch: "v4.1.x"
          openpmix_branch: "v4.2.2"
          coverage: false
          env: {}
        - name: "focal - ompi v4.0.x"
          image: "focal"
          ompi_branch: "v4.0.x"
          openpmix_branch: "v4.2.2"
          coverage: false
          env: {}
        - name: "focal - ompi v3.1.x"
          image: "focal"
          ompi_branch: "v3.1.x"
          openpmix_branch: "v4.2.2"
          coverage: false
          env: {}
        - name: "focal - ompi v3.0.x"
          image: "focal"
          ompi_branch: "v3.0.x"
          openpmix_branch: "v4.2.2"
          coverage: false
          env: {}

      fail-fast: false
    name: ${{ matrix.name }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
       ref: ${{ github.event.pull_request.head.sha }}
       fetch-depth: 0

    - name: fetch annotated tag
      if: matrix.create_release && startswith(github.ref, 'refs/tags')
      run: |
        # Ensure git-describe works on a tag.
        #  (checkout@v4 action may have left current tag as
        #   lightweight instead of annotated. See
        #   https://github.com/actions/checkout/issues/290)
        #
        echo github.ref == ${{ github.ref }} ;
        git fetch -f origin ${{ github.ref }}:${{ github.ref }} ;
        echo git describe now reports $(git describe --always)

    - name: get tag name
      id: tag
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >$GITHUB_OUTPUT

    - name: docker-run-checks
      env: ${{ matrix.env }}
      run: >
        ./src/test/docker/docker-run-checks.sh
        -j $(nproc)
        -i ${{ matrix.image }}
        --build-arg OMPI_BRANCH=${{ matrix.ompi_branch }}
        --build-arg OPENPMIX_BRANCH=${{ matrix.openpmix_branch }}
        --

    - name: annotate errors
      if: failure() || cancelled()
      run: src/test/checks-annotate.sh

    - name: coverage report
      if: success() && matrix.coverage
      env:
        DOCKER_REPO:
      uses: codecov/codecov-action@858dd794fbb81941b6d60b0dca860878cba60fa9 # v3.1.1

    - name: create release
      id: create_release
      if: |
        success()
        && matrix.create_release
        && startswith(github.ref, 'refs/tags')
        && github.repository == 'flux-framework/flux-pmix'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.output.TAG }}
        name: flux-pmix ${{ steps.tag.output.TAG }}
        prerelease: true
        files: flux-pmix*.tar.gz
        body: |
          View [Release Notes](https://github.com/${{ github.repository }}/blob/${{ matrix.tag }}/NEWS.md) for flux-pmix ${{ steps.tag.output.TAG }}
